###############################################################################
#
# HOW TO USE
#
# Go to the "Actions" tab in the repository
# In the left sidebar, select this workflow
# Above the list of workflow runs, select "Run workflow".
#
###############################################################################

name: Windows Dependencies

on: workflow_dispatch

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "x64", triplet: x64-windows-release }
          - { name: "x86", triplet: x86-windows-release }

    steps:
      - uses: actions/checkout@v3

      - name: Update vcpkg
        run: |
          cd $VCPKG_INSTALLATION_ROOT
          git pull
          ./bootstrap-vcpkg.bat

      - name: Build
        working-directory: prboom2
        run: |
          vcpkg install \
            --triplet=${{ matrix.config.triplet }} \
            --host-triplet=${{ matrix.config.triplet }} \
            --x-feature="dumb" \
            --x-feature="fluidsynth" \
            --x-feature="libmad" \
            --x-feature="libvorbis" \
            --x-feature="portmidi" \
            --x-feature="sdl2-image"

      - name: Copy dependencies
        run: |
          mkdir -p output/dependencies_${{ matrix.config.name }}
          mv prboom2/vcpkg_installed/${{ matrix.config.triplet }}/{include,lib,share} \
             output/dependencies_${{ matrix.config.name }}

          if [[ -d prboom2/vcpkg_installed/${{ matrix.config.triplet }}/bin ]]; then
            mkdir -p output/dependencies_${{ matrix.config.name }}/bin
            mv prboom2/vcpkg_installed/${{ matrix.config.triplet }}/bin/*.dll \
               output/dependencies_${{ matrix.config.name }}/bin
          fi

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: output/*
          name: windows_dependencies
